[project]
name = "cmeel-boost"
version = "1.80.0.1"
description = "cmeel distribution for boost, which provides free peer-reviewed portable C++ source libraries."
readme = "README.md"
requires-python = ">= 3.7"
license = "BSL-1.0"
dependencies = ['numpy']

[project.urls]
homepage = "https://github.com/cmeel/cmeel-boost"
repository = "https://github.com/cmeel/cmeel-boost.git"

[tool.cmeel]
run-tests = false
build-number = 2

[build-system]
requires = ["cmeel[build]", 'numpy']
build-backend = "cmeel.build"
