[project]
name = "cmeel-boost"
version = "1.80.0"
description = "cmeel distribution for boost, which provides free peer-reviewed portable C++ source libraries."
readme = "README.md"
requires-python = ">= 3.7"
license = "BSL-1.0"
dependencies = ['numpy == 1.23.4 ; python_version > "3.7"', 'numpy == 1.21.6 ; python_version < "3.8"']

[project.urls]
homepage = "https://github.com/cmeel/cmeel-boost"
repository = "https://github.com/cmeel/cmeel-boost.git"

[tool.cmeel]
build-number = 3
run-tests = false

[build-system]
requires = ["cmeel[build]", 'numpy == 1.23.4 ; python_version > "3.7"', 'numpy == 1.21.6 ; python_version < "3.8"']
build-backend = "cmeel.build"
