[build-system]
build-backend = "cmeel"
requires = [
  "cmeel[build]",
  "numpy>=2.0",
]

[project]
dependencies = [
  "numpy>=2.0",
]
description = "cmeel distribution for boost, which provides free peer-reviewed portable C++ source libraries."
license = "BSL-1.0"
name = "cmeel-boost"
requires-python = ">= 3.10"
version = "1.90.0"

[project.urls]
homepage = "https://github.com/cmake-wheel/cmeel-boost"
repository = "https://github.com/cmake-wheel/cmeel-boost.git"
upstream = "https://www.boost.org/"

[tool.cmeel]
run-tests = false

[tool.tomlsort]
all = true
trailing_comma_inline_array = true
